CREATE TABLE IF NOT EXISTS order_items(
    id SERIAL PRIMARY KEY,
    orderId INTEGER NOT NULL,
    productId INTEGER NOT NULL,
    quantity   INTEGER NOT NULL,
    price   DECIMAL(10,2) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_orderid FOREIGN KEY(orderId) REFERENCES ORDERS(id),
    CONSTRAINT fk_productid FOREIGN KEY(productId) REFERENCES PRODUCTS(id)
);